#!/usr/bin/env python3
"""
spectrum_pilot.py -- PREVIEW the governance spectrum (G0..G4) on the questions already
served, WITHOUT touching frozen Q6. Produces the risk-coverage frontier so you can SEE
the shape before the Dr. Xu conversation.

Pilot fidelity (disclosed): G0/G3/G4 reuse existing outputs; G1/G2 are generated by a
harness generator that mirrors Q6's synthesis prompt but relaxes the evidence gate. The
PRODUCTION version parameterizes Q6 (pending Dr. Xu). Every governed level still cites
[CHNK_*] provenance.

LEVELS (evidence to answer; else abstain):
  G0 Naive        : raw docs (no citation)              -> reuse serve_results.naive
  G1 Cited        : all retrieved chunks (Q3), cite     -> generate
  G2 Grounded     : authorized chunks (Q5), cite        -> generate; abstain if none
  G3 Strict       : >=1 authorized triplet (Q6)         -> reuse serve_results.governed
  G4 Corroborated : >=2 authorized triplets             -> reuse G3 answer, else abstain

INPUTS (from the last serve run, in repo):
  results/serve_results.jsonl, output/Q3_retrieved_evidence.jsonl,
  output/Q5_routed_context.jsonl, results/gold_map.json
OUTPUT: results/spectrum_frontier.csv (+ .png if matplotlib), results/spectrum_scores.jsonl

RUN from repo root:
  python spectrum_pilot.py --model gemini-3.5-flash --judge-model gemini-2.5-pro --runs 1
"""
import argparse, json, os, statistics as st, sys
import trace_scorer as ts   # reuse correctness(), judge_tuple(), norm_q(), is_refusal()

LEVELS = ["G0_Naive", "G1_Cited", "G2_Grounded", "G3_Strict", "G4_Corroborated"]
REFUSE = "Governance Boundary: Evidence insufficient."

GEN_PROMPT = """Answer the QUESTION using ONLY the EVIDENCE below.
Rules: (1) direct, concise answer; (2) you MUST cite sources using the [CHNK_...] tags
shown in the evidence; (3) do not use outside knowledge; (4) if the evidence does not
contain the answer, reply exactly: "%s"

EVIDENCE:
%s

QUESTION: %s""" % ("%s", "%s", "%s")


def load_jsonl(p):
    out = {}
    rows = []
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            if line.strip():
                rows.append(json.loads(line))
    return rows


def by_record(rows):
    m = {}
    for r in rows:
        rid = str(r.get("record_id"))
        m[rid] = r
    return m


def gen(client, types, model, question, evidence):
    if not (evidence or "").strip():
        return REFUSE, True
    prompt = GEN_PROMPT % (REFUSE, evidence[:12000], question)
    try:
        r = client.models.generate_content(model=model, contents=prompt,
                config=types.GenerateContentConfig(temperature=0.0))
        a = (r.text or "").strip()
    except Exception as e:
        return "ERROR: %s" % e, True
    return a, ts.is_refusal(a)


def build_levels(row, q3, q5, client, types, model):
    """Return {level: (answer, refused, context_for_trace, gov_ratio_or_None)}."""
    idx = str(row.get("idx"))
    rid = "delucionqa_q%05d" % int(idx)
    q = row.get("question", "")
    naive = row.get("naive", {}); gov = row.get("governed", {})
    e3 = q3.get(rid, {}); e5 = q5.get(rid, {})
    ctx_all = str(e3.get("semantic_chunk", "") or "")          # G1 evidence (pre-auth, labeled)
    ctx_auth = str(e5.get("semantic_chunk", "") or "")         # G2 evidence (authorized, labeled)
    n_trip = len(e5.get("symbolic_triplets", []) or [])        # authorized triplets
    gr = e5.get("gov_ratio")

    lv = {}
    # G0 Naive
    lv["G0_Naive"] = (naive.get("answer", ""), ts.is_refusal(naive.get("answer", "")), naive.get("context", ""), None)
    # G1 Cited (all retrieved chunks)
    a1, r1 = gen(client, types, model, q, ctx_all)
    lv["G1_Cited"] = (a1, r1, ctx_all, gr)
    # G2 Grounded (authorized chunks)
    a2, r2 = gen(client, types, model, q, ctx_auth)
    lv["G2_Grounded"] = (a2, r2, ctx_auth, gr)
    # G3 Strict (reuse)
    g_ans = gov.get("answer", ""); g_ref = bool(gov.get("refused")) or ts.is_refusal(g_ans, gov.get("mode", ""))
    lv["G3_Strict"] = (g_ans, g_ref, gov.get("context", "") or ctx_auth, gov.get("governance_ratio"))
    # G4 Corroborated (>=2 authorized triplets)
    if n_trip >= 2 and not g_ref:
        lv["G4_Corroborated"] = (g_ans, False, gov.get("context", "") or ctx_auth, gov.get("governance_ratio"))
    else:
        lv["G4_Corroborated"] = (REFUSE, True, ctx_auth, gr)
    return lv


def score_level(client, types, judge, gold, answerable, answer, refused, context):
    verdict = "SAFE_SILENCE" if refused else ts.correctness(gold, answer, "", judge, client, types)
    trace = None
    if not refused:
        trace = ts.judge_tuple("", context, answer, judge, client, types)
    return verdict, trace


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--serve", default="results/serve_results.jsonl")
    ap.add_argument("--q3", default="output/Q3_retrieved_evidence.jsonl")
    ap.add_argument("--q5", default="output/Q5_routed_context.jsonl")
    ap.add_argument("--gold-map", default="results/gold_map.json")
    ap.add_argument("--model", default="gemini-3.5-flash")
    ap.add_argument("--judge-model", default="gemini-2.5-pro")
    ap.add_argument("--runs", type=int, default=1)
    args = ap.parse_args()

    from google import genai
    from google.genai import types
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    serve = load_jsonl(args.serve)
    q3 = by_record(load_jsonl(args.q3))
    q5 = by_record(load_jsonl(args.q5))
    gold_map = json.load(open(args.gold_map, encoding="utf-8")) if os.path.exists(args.gold_map) else {}
    print("[pilot] %d served questions | q3=%d q5=%d gold=%d | model=%s judge=%s runs=%d"
          % (len(serve), len(q3), len(q5), len(gold_map), args.model, args.judge_model, args.runs))

    # accumulate over runs
    per_level = {L: {"answered": 0, "adh_total": 0, "adh_match": 0, "faith": [], "total": 0} for L in LEVELS}
    detail = []
    for run in range(args.runs):
        print("  run %d/%d" % (run + 1, args.runs))
        for row in serve:
            q = row.get("question", "")
            g = gold_map.get(ts.norm_q(q), {})
            gold = g.get("gold_response", row.get("gold", "")); answerable = g.get("answerable")
            lv = build_levels(row, q3, q5, client, types, args.model)
            rec = {"idx": row.get("idx"), "question": q, "answerable": answerable, "run": run, "levels": {}}
            for L in LEVELS:
                ans, ref, ctx, gr = lv[L]
                verdict, trace = score_level(client, types, args.judge_model, gold, answerable, ans, ref, ctx)
                s = per_level[L]; s["total"] += 1
                if not ref:
                    s["answered"] += 1
                    if trace:
                        s["faith"].append(trace["adherence"])
                if answerable is True:               # answer-match only on adherent stratum
                    s["adh_total"] += 1
                    if verdict == "MATCH":
                        s["adh_match"] += 1
                rec["levels"][L] = {"refused": ref, "verdict": verdict,
                                    "adherence": (trace["adherence"] if trace else None), "gov_ratio": gr}
            detail.append(rec)

    os.makedirs("results", exist_ok=True)
    with open("results/spectrum_scores.jsonl", "w", encoding="utf-8") as f:
        for r in detail:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    # frontier table
    print("\n" + "=" * 74)
    print("GOVERNANCE SPECTRUM — risk-coverage frontier   (%d Q x %d run)" % (len(serve), args.runs))
    print("=" * 74)
    print("%-16s %10s %14s %14s" % ("level", "coverage", "accuracy(adh)", "faithfulness"))
    rows_csv = [("level", "coverage", "accuracy_adherent", "faithfulness_adherence")]
    for L in LEVELS:
        s = per_level[L]
        cov = s["answered"] / s["total"] if s["total"] else 0.0
        acc = s["adh_match"] / s["adh_total"] if s["adh_total"] else 0.0
        faith = st.mean(s["faith"]) if s["faith"] else float("nan")
        print("%-16s %9.0f%% %13.0f%% %14.3f" % (L, 100 * cov, 100 * acc, faith))
        rows_csv.append((L, "%.4f" % cov, "%.4f" % acc, "%.4f" % (faith if faith == faith else 0)))
    with open("results/spectrum_frontier.csv", "w", encoding="utf-8") as f:
        for r in rows_csv:
            f.write(",".join(map(str, r)) + "\n")
    print("-" * 74)
    print("READ: coverage should fall G0->G4; accuracy/faithfulness should rise. The KNEE is the")
    print("      operating point. (Pilot: G1/G2 harness-generated; production parameterizes Q6.)")

    # optional plot
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        xs = [per_level[L]["answered"] / per_level[L]["total"] if per_level[L]["total"] else 0 for L in LEVELS]
        ys = [per_level[L]["adh_match"] / per_level[L]["adh_total"] if per_level[L]["adh_total"] else 0 for L in LEVELS]
        plt.figure(figsize=(6, 4.2))
        plt.plot(xs, ys, "-o", color="#2E75B6")
        for L, x, y in zip(LEVELS, xs, ys):
            plt.annotate(L.split("_")[0], (x, y), textcoords="offset points", xytext=(6, 5))
        plt.xlabel("Coverage (answer rate)"); plt.ylabel("Accuracy on adherent stratum")
        plt.title("Governance spectrum: risk-coverage frontier (pilot)")
        plt.grid(alpha=0.3); plt.tight_layout()
        plt.savefig("results/spectrum_frontier.png", dpi=150)
        print("[pilot] plot -> results/spectrum_frontier.png")
    except Exception as e:
        print("[pilot] plot skipped (%s); CSV written -> results/spectrum_frontier.csv" % e)


if __name__ == "__main__":
    main()
